# Generated by Django 5.1.6 on 2025-03-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tool", "0002_userprofile_fathers_name_alter_userprofile_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="location",
            new_name="city",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bin",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="education",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="institution",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="sex",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="specialization",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
