# Generated by Django 5.1.6 on 2025-03-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tool", "0003_rename_location_userprofile_city_userprofile_bin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="tech_stack",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tech_stack",
            field=models.ManyToManyField(to="tool.techstack"),
        ),
    ]
