# Generated by Django 5.1.6 on 2025-03-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tool", "0004_remove_userprofile_tech_stack_userprofile_tech_stack"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="resume",
            field=models.TextField(blank=True),
        ),
    ]
