# Generated by Django 5.1.6 on 2025-03-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_educationalinstitution_privateemployer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='link',
        ),
        migrations.AddField(
            model_name='company',
            name='link',
            field=models.ManyToManyField(blank=True, to='tool.links'),
        ),
    ]
