# Generated by Django 5.1.6 on 2025-04-13 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tool", "0007_links_remove_company_link_company_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="Unknown", max_length=100),
                ),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                ("experience", models.IntegerField(blank=True, null=True)),
                ("skills", models.CharField(blank=True, max_length=100, null=True)),
                ("responsibilities", models.TextField(blank=True, null=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("salary", models.IntegerField(blank=True, null=True)),
                ("compensation", models.IntegerField(blank=True, null=True)),
                ("work_conditions", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="EducationalInstitution",
        ),
        migrations.RemoveField(
            model_name="application",
            name="job",
        ),
        migrations.AddField(
            model_name="application",
            name="Vacancy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tool.vacancy",
            ),
        ),
        migrations.DeleteModel(
            name="Job",
        ),
    ]
